test: deploy job

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,7 +28,7 @@ env:
   ECR_REPOSITORY: dwp/np/auth            # <- change to your ECR repository name
   GIT_USER_NAME: "ci-bot"
   GIT_USER_EMAIL: "ci-bot@devopswithprashant.com"
-  #GITOPS_BRANCH_NAME: ""  # <- change to your gitops branch name or set as repo variable
+  GITOPS_BRANCH_NAME: "feat/auth-integration"  # <- change to your gitops branch name or set as repo variable
 
 
 
@@ -147,102 +147,102 @@ jobs:
           cache-to: type=gha,mode=max
 
   
-  # deploy-DEV:
-  #   if: ${{ !startsWith(github.event.head_commit.message, '[Gradle Release Plugin]') }}
-  #   needs: [maven, docker]
-  #   runs-on: ubuntu-latest
-  #   defaults:
-  #     run:
-  #       shell: bash
-  #   steps:
-  #   # Checkout the repository to the GitHub Actions runner
-  #     - name: Checkout gitops repo
-  #       uses: actions/checkout@v4
-  #       with:
-  #         repository: "devopswithprashant/k8-blogApp"
-  #         token: ${{ secrets.GHEC_TOKEN_K8 }}
-  #         ref: ${{ env.GITOPS_BRANCH_NAME }}
-  #         fetch-depth: 10
+  deploy-DEV:
+    if: ${{ !startsWith(github.event.head_commit.message, '[Gradle Release Plugin]') }}
+    needs: [gradle, docker]
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+    steps:
+    # Checkout the repository to the GitHub Actions runner
+      - name: Checkout gitops repo
+        uses: actions/checkout@v6
+        with:
+          repository: "devopswithprashant/k8-blogApp"
+          token: ${{ secrets.GHEC_TOKEN_K8 }}
+          ref: ${{ env.GITOPS_BRANCH_NAME }}
+          fetch-depth: 10
 
-  #     - name: Update image tag in target file
-  #       #working-directory: gitops
-  #       id: update
-  #       env:
-  #         FILE: "env/dev/blog-deployment.yaml"
-  #         IMAGE: "850756192530.dkr.ecr.us-east-1.amazonaws.com/dwp/np/blog"
-  #         NEW_TAG: ${{ needs.maven.outputs.projectVersion }}-${{ github.sha }}
+      - name: Update image tag in target file
+        #working-directory: gitops
+        id: update
+        env:
+          FILE: "env/dev/auth-deployment.yaml"
+          IMAGE: "850756192530.dkr.ecr.us-east-1.amazonaws.com/dwp/np/auth"
+          NEW_TAG: ${{ needs.gradle.outputs.projectVersion }}-${{ github.sha }}
           
-  #       run: |
-  #         set -euo pipefail
-  #         if [ ! -f "$FILE" ]; then
-  #           echo "ERROR target file not found: $FILE"
-  #           exit 1
-  #         fi
-  #         NEW_IMAGE="${IMAGE}:${NEW_TAG}"
-  #         sed -E -i "s|850756192530\.dkr\.ecr\.us-east-1\.amazonaws\.com/dwp(/np)?/blog:[^[:space:]]+|${NEW_IMAGE}|g" "$FILE"
-  #         # Git config
-  #         git config user.name "${GIT_USER_NAME}"
-  #         git config user.email "${GIT_USER_EMAIL}"
-  #         # Check if file actually changed before committing
-  #         if git diff --quiet -- "$FILE"; then
-  #           echo "✅ No changes detected in $FILE — skipping commit & push."
-  #           exit 0
-  #         fi
-  #         git add "$FILE"
-  #         if git diff --cached --quiet; then
-  #           echo "✅ Nothing new to commit — skipping push."
-  #           exit 0
-  #         fi
-  #         git commit -m "chore(DEV): bump new version ${NEW_TAG} of blog image ${IMAGE}"
-  #         git push origin ${{ env.GITOPS_BRANCH_NAME }}
+        run: |
+          set -euo pipefail
+          if [ ! -f "$FILE" ]; then
+            echo "ERROR target file not found: $FILE"
+            exit 1
+          fi
+          NEW_IMAGE="${IMAGE}:${NEW_TAG}"
+          sed -E -i "s|850756192530\.dkr\.ecr\.us-east-1\.amazonaws\.com/dwp(/np)?/auth:[^[:space:]]+|${NEW_IMAGE}|g" "$FILE"
+          # Git config
+          git config user.name "${GIT_USER_NAME}"
+          git config user.email "${GIT_USER_EMAIL}"
+          # Check if file actually changed before committing
+          if git diff --quiet -- "$FILE"; then
+            echo "✅ No changes detected in $FILE — skipping commit & push."
+            exit 0
+          fi
+          git add "$FILE"
+          if git diff --cached --quiet; then
+            echo "✅ Nothing new to commit — skipping push."
+            exit 0
+          fi
+          git commit -m "chore(DEV): bump new version ${NEW_TAG} of auth image ${IMAGE}"
+          git push origin ${{ env.GITOPS_BRANCH_NAME }}
 
 
-  # deploy-QA:
-  #   if: ${{ !startsWith(github.event.head_commit.message, '[Gradle Release Plugin]') }}
-  #   needs: [maven, docker, deploy-DEV]
-  #   runs-on: ubuntu-latest
-  #   defaults:
-  #     run:
-  #       shell: bash
-  #   steps:
-  #   # Checkout the repository to the GitHub Actions runner
-  #     - name: Checkout gitops repo
-  #       uses: actions/checkout@v4
-  #       with:
-  #         repository: "devopswithprashant/k8-blogApp"
-  #         token: ${{ secrets.GHEC_TOKEN_K8 }}
-  #         ref: ${{ env.GITOPS_BRANCH_NAME }}
-  #         fetch-depth: 10
+  deploy-QA:
+    if: ${{ !startsWith(github.event.head_commit.message, '[Gradle Release Plugin]') }}
+    needs: [gradle, docker, deploy-DEV]
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+    steps:
+    # Checkout the repository to the GitHub Actions runner
+      - name: Checkout gitops repo
+        uses: actions/checkout@v5
+        with:
+          repository: "devopswithprashant/k8-blogApp"
+          token: ${{ secrets.GHEC_TOKEN_K8 }}
+          ref: ${{ env.GITOPS_BRANCH_NAME }}
+          fetch-depth: 10
 
-  #     - name: Update image tag in target file
-  #       #working-directory: gitops
-  #       id: update
-  #       env:
-  #         FILE: "env/qa/blog-deployment.yaml"
-  #         IMAGE: "850756192530.dkr.ecr.us-east-1.amazonaws.com/dwp/np/blog"
-  #         NEW_TAG: ${{ needs.maven.outputs.projectVersion }}-${{ github.sha }}
-  #       run: |
-  #         set -euo pipefail
-  #         if [ ! -f "$FILE" ]; then
-  #           echo "ERROR target file not found: $FILE"
-  #           exit 1
-  #         fi
-  #         NEW_IMAGE="${IMAGE}:${NEW_TAG}"
-  #         sed -E -i "s|850756192530\.dkr\.ecr\.us-east-1\.amazonaws\.com/dwp(/np)?/blog:[^[:space:]]+|${NEW_IMAGE}|g" "$FILE"
-  #         # Git config
-  #         git config user.name "${GIT_USER_NAME}"
-  #         git config user.email "${GIT_USER_EMAIL}"
-  #         # Check if file actually changed before committing
-  #         if git diff --quiet -- "$FILE"; then
-  #           echo "✅ No changes detected in $FILE — skipping commit & push."
-  #           exit 0
-  #         fi
-  #         git add "$FILE"
-  #         if git diff --cached --quiet; then
-  #           echo "✅ Nothing new to commit — skipping push."
-  #           exit 0
-  #         fi
-  #         git commit -m "chore(QA): bump new version ${NEW_TAG} of blog image ${IMAGE}"
-  #         git push origin ${{ env.GITOPS_BRANCH_NAME }}
+      - name: Update image tag in target file
+        #working-directory: gitops
+        id: update
+        env:
+          FILE: "env/qa/auth-deployment.yaml"
+          IMAGE: "850756192530.dkr.ecr.us-east-1.amazonaws.com/dwp/np/auth"
+          NEW_TAG: ${{ needs.gradle.outputs.projectVersion }}-${{ github.sha }}
+        run: |
+          set -euo pipefail
+          if [ ! -f "$FILE" ]; then
+            echo "ERROR target file not found: $FILE"
+            exit 1
+          fi
+          NEW_IMAGE="${IMAGE}:${NEW_TAG}"
+          sed -E -i "s|850756192530\.dkr\.ecr\.us-east-1\.amazonaws\.com/dwp(/np)?/auth:[^[:space:]]+|${NEW_IMAGE}|g" "$FILE"
+          # Git config
+          git config user.name "${GIT_USER_NAME}"
+          git config user.email "${GIT_USER_EMAIL}"
+          # Check if file actually changed before committing
+          if git diff --quiet -- "$FILE"; then
+            echo "✅ No changes detected in $FILE — skipping commit & push."
+            exit 0
+          fi
+          git add "$FILE"
+          if git diff --cached --quiet; then
+            echo "✅ Nothing new to commit — skipping push."
+            exit 0
+          fi
+          git commit -m "chore(QA): bump new version ${NEW_TAG} of auth image ${IMAGE}"
+          git push origin ${{ env.GITOPS_BRANCH_NAME }}
 
       
